;; feeds.el
(setq feeds
      '(("http://feeds.feedburner.com/amirmc" tech)
        ("http://sachachua.com/blog/feed" tech)
        ("http://medium.com/feed/@jlouis666" tech)
        ("http://psnively.github.com/atom.xml" tech)
        ("http://www.drmaciver.com/feed/" tech)
        ("http://davehakkens.nl/feed/" tech)
        ("http://www.defmacro.org/feed.atom" tech)
        ("http://feeds.feedburner.com/holman" tech)
        ("http://worrydream.com/feed.xml" tech)
        ("http://caitiem.com/feed/" tech)
        ("http://feeds.feedburner.com/tom-preston-werner" tech)
        ("http://mads379.github.io/feed.xml" tech)
        ("http://logicaltypes.blogspot.com/feeds/posts/default?alt=rss" tech)
        ("http://anil.recoil.org/feeds/atom.xml" tech)
        ("http://feeds.feedburner.com/threeriversinstitute/khkV" tech)
        ("http://nerds.airbnb.com/feed/" company)
        ("http://stripe.com/blog/feed.rss" company)
        ("http://blog.alfredapp.com/feed/" company)
        ("http://github.com/blog.atom" company)
        ("http://techblog.netflix.com/feeds/posts/default" company)
        ("http://www.paus.dk/blog?format=RSS" misc)
        ("http://designairs.com/feed/" company)
        ("http://ocaml.janestreet.com/?q=rss.xml" company)
        ("http://functionaltalks.org/feed.xml" programming)
        ("http://googleonlinesecurity.blogspot.com/feeds/posts/default" programming)
        ("http://www.openmirage.org/blog/atom.xml" programming)
        ("http://planet.ocamlcore.org/atom.xml" programming)
        ("http://okmij.org/ftp/rss.xml" programming)
        ("http://emacsrocks.com/atom.xml" misc emacs)
        ("http://endlessparentheses.com/atom.xml" emacs)
        ("http://emacsrocks.com/atom.xml" emacs)
        ("http://planet.emacsen.org/atom.xml" emacs)
        ("http://whattheemacsd.com/atom.xml" emacs)
        ("http://www.lunaryorn.com/feed.atom" emacs ocaml)
        ("http://folkelab.dk/feed/atom.xml" misc)
        ("http://feeds.wnyc.org/radiolab" misc)
        ("http://blog.genbyg.dk/feed/" misc)
        ("http://logicaltypes.blogspot.com/feeds/posts/default?alt=rss" programming)
        ("http://anil.recoil.org/feeds/atom.xml" tech ocaml)
        ("http://www.somerandomidiot.com/atom.xml" tech ocaml)
        ("http://davehakkens.nl/feed/" misc)
        ("http://www.masteringemacs.org/feed/" tech)
        ("http://firstlook.org/theintercept/feed/" news)
        ("http://www.schneier.com/blog/atom.xml" tech security)
        ("http://feeds.feedburner.com/TroyHunt" tech security)
        ("http://lambda-the-ultimate.org/rss.xml" tech programming-languages)
        ("http://politiken.dk/rss/ibyen.rss")
        ("http://soundvenue.com/category/musik/feed" music)
        ("http://www.slow-journalism.com/feed" news)
        ("https://syntaxexclamation.wordpress.com/feed/" programming)
        ("https://algorithms.rdio.com/atom.xml" tech)))

;;;###autoload
(provide 'feeds)
